%YAML 1.1
---

#### Retention Configuration ####

elastic_close_interval: 15
elastic_delete_interval: 60


#### Main Role Configuration ####

es_user: 1000
es_group: 1000
es_cluster_name: rocknsm
es_mem: "{{ (ansible_memtotal_mb // 1024 // 2) if (ansible_memtotal_mb // 1024) < 64 else 31 }}"
elastic_data_port: '9200'
elastic_management_port: '9300'
elastic_container: 'docker.elastic.co/elasticsearch/elasticsearch'
elastic_container_name: 'elasticsearch'
es_log_dir: '/var/log/elasticsearch'

elastic_dir: "{{ rocknsm_dir  }}/elasticsearch"
elastic_vol_size: 1
elastic_vol_name: "elastic-data"
scaleio_pd_name: "default"
scaleio_sp_name: "default"
scaleio_gateway_url: "https://localhost:443/api"
elastic_pv_data: "elastic-data"
elastic_pv_data_dir: "{{ elastic_dir }}/data"
elastic_pv_data_path: "/usr/share/elasticsearch/data"
elastic_config_map: "elastic-config"
elastic_config_dir: "{{ elastic_dir }}/config"
elastic_config_path: "/usr/share/elasticsearch/config"
