%YAML 1.1
---

#### Retention Configuration ####

elastic_close_interval: 15
elastic_delete_interval: 60


#### Main Role Configuration ####

elastic_baseurl: https://artifacts.elastic.co/packages/5.x/yum
elastic_gpgurl: https://artifacts.elastic.co/GPG-KEY-elasticsearch
es_user: elasticsearch
es_group: elasticsearch
es_data_dir: "{{ rock_data_dir }}/elasticsearch"
es_cluster_name: rocknsm
es_mem: "{{ (ansible_memtotal_mb // 1024 // 2) if (ansible_memtotal_mb // 1024) < 64 else 31 }}"
es_node_name: "{{ rock_hostname }}"
es_memlock_override: |
  [Service]
  LimitMEMLOCK=infinity

elastic_ver: '6.1.1'
elastic_data_port: '9200'
elastic_management_port: '9300'
elastic_container: 'docker.elastic.co/elasticsearch/elasticsearch'
elastic_yum: 'elastic'
elastic_config_file: '/etc/elasticsearch/elasticsearch.yml'
elastic_override_dir: '/etc/systemd/system/elasticsearch.service.d'
es_config_dir: '/etc/elasticsearch'
