######################################################
################# Setup Ceph #########################
######################################################
---

- import_tasks: 00_preflight.yml

- name: Ceph Deploy Block
  block:
    - import_tasks: 05_files.yml
    - import_tasks: 10_install.yml
    - import_tasks: 15_setup.yml
    - import_tasks: 20_deploy.yml
    - import_tasks: 25_validate.yml
  any_errors_fatal: true
  when: (kube_check_result is defined and kube_check_result.stdout == "")
    or (ceph_status_result is defined and 'HEALTH_ERR' in ceph_status_result.stdout)
    or (ceph_status_result is defined and 'HEALTH_WARN' in ceph_status_result.stdout)
    or (reinstall is defined and reinstall)
