#######################################################
#################### DNS Changes ######################
#######################################################
---
- name: Change the hostname to our standard
  hostname:
    name="{{ inventory_hostname }}"
  register: hostname

- name: Validate ansible_fqdn == inventory_hostname
  tags:
    - validate
  assert:
    that:
      ansible_fqdn == inventory_hostname