---

- name: Configure packages for CentOS
  set_fact:
    rocknsm_package_list: "{{ centos_package_list }} + [ '{{ item.pkg }}']"
  when: (ansible_distribution == "CentOS") and ((item.test is undefined) or (item.test))
  with_items:
    - { pkg: chrony, state: installed }
# TODO: These lines need to be moved to the sensor common
#    - { pkg: daq, test: "{{with_snort}}", state: installed }
    - { pkg: postfix, state: installed }
#    - { pkg: snort, test: "{{with_snort}}", state: installed }

- name: Configure packages for Red Hat
  set_fact:
    rocknsm_package_list: "{{ centos_package_list }} + [ '{{ item.pkg }}']"
  when: (ansible_distribution == "RedHat") and ((item.test is undefined) or (item.test))
  with_items:
    - { pkg: chrony, state: installed }
# TODO: These lines need to be moved to the sensor common
#    - { pkg: daq, test: "{{with_snort}}", state: installed }
    - { pkg: postfix, state: installed }
#    - { pkg: snort, test: "{{with_snort}}", state: installed }

- name: Install packages
  yum:
    name: "{{ item.pkg }}"
    state: "{{ item.state }}"
  when: (item.test is undefined) or (item.test)
  with_items:
    - { pkg: "{{ rocknsm_package_list }}", state: installed }
