######################################################
############### ROCKNSM Customization ################
######################################################
- name: "Build hosts file"
  template:
    dest: '/etc/hosts'
    src: 'hosts.j2'

- name: "Add Deployer to hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*deployer.lan$'
    line: "{{ deployer }} deployer deployer.lan"
    state: present
  when: deployer is defined

# main.yml - Common tasks for ROCK
- include_tasks: set_hostname.yml
- include_tasks: minimum_hardware_check.yml
- include_tasks: ssh_host_keys.yml
- include_tasks: configure_yum_repos.yml
- include_tasks: configure_rock_repo.yml
- include_tasks: disable_selinux.yml
- include_tasks: install_common_packages.yml
- include_tasks: create_directories.yml
- include_tasks: disable_ipv6.yml
- include_tasks: disable_firewall.yml
#- include_tasks: ensure_cache_directory_exists.yml
#- include_tasks: enable_firewall.yml
- include_tasks: reboot.yml