######################################################
############### ROCKNSM Customization ################
######################################################
- name: "Build hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].management_ipv4 }} {{ hostvars[item].inventory_hostname_short }} {{item}}"
    state: present
  when: hostvars[item].management_ipv4 is defined
  with_items: "{{ groups['all'] }}"

- name: "Add Deployer to hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*deployer.lan$'
    line: "{{ deployer }} deployer deployer.lan"
    state: present
  when: deployer is defined

- name: Install ROCK NSM /etc/issue
  copy:
    src: etc-issue.in
    dest: /etc/issue.in
    mode: 0644
    owner: root
    group: root

- name: NetworkManager ROCK NSM hook
  copy:
    src: nm-issue-update
    dest: /etc/NetworkManager/dispatcher.d/50-rocknsm-issue-update
    mode: 0755
    owner: root
    group: root

# main.yml - Common tasks for ROCK
- include_tasks: minimum_hardware_check.yml
- include_tasks: ssh_host_keys.yml
- include_tasks: configure_yum_repos.yml
- include_tasks: configure_rock_repo.yml
- include_tasks: install_common_packages.yml
- include_tasks: create_directories.yml
- include_tasks: disable_ipv6.yml
- include_tasks: set_hostname.yml
#- include_tasks: ensure_cache_directory_exists.yml
#- include_tasks: enable_firewall.yml
- include_tasks: install_docker.yml
