#############################################################
############ Verify Server Hardware Requirements ############
#############################################################
---

- assert:
    that:
      - ansible_memtotal_mb >= {{ 2048 * 0.90 }}
    msg: "Not enough RAM (2GB+ required)! Aborting server install."
  when: serverlocal is defined and serverlocal

- assert:
    that:
      - ({{ ansible_processor_cores }} * {{ ansible_processor_count }}) >= 2
    msg: "Not enough CPU Cores (2+ required)! Aborting server install."
  when: serverlocal is defined and serverlocal
