---

- name: Gather ssh host keys
  shell: "echo \"{{ inventory_hostname_short }},{{ inventory_hostname }} $(cat /etc/ssh/ssh_host_ecdsa_key.pub)\""
  register: ssh_host_keys

- name: Combine keys
  set_fact:
    host_keys: "{{ ansible_play_hosts | map('extract', hostvars, 'ssh_host_keys') | map(attribute='stdout') | list }}"
  run_once: yes

- name: Propagate ssh host keys
  lineinfile:
    line: "{{ item }}"
    path: "/etc/ssh/ssh_known_hosts"
    state: present
    create: yes
  with_items:
    - "{{ host_keys }}"

- name: Remove possible conflicting host keys from profile
  file:
    path: "/root/.ssh/known_hosts"
    state: absent