%YAML 1.1
---

#### Main Role Configuration ####

kafka_user: kafka
kafka_group: kafka
kafka_container_name: 'rock-kafka'
kafka_dir: "{{ rocknsm_dir }}/kafka"
kafka_data_dir: "{{ rock_data_dir }}/kafka"
kafka_port: 9092
kafka_maj_vsn: 1.0.0
kafka_vsn: "2.12-{{ kafka_maj_vsn }}"
kafka_install_dir: '/opt/kafka'
kafka_log_dir: '/var/log/kafka'
