######################################################
################# Setup Elasticsearch ################
######################################################
---

# - include_tasks: 'enable_firewall.yml'

- include_tasks: 'elastic_bare-metal.yml'
  when: not containerized_install

- include_tasks: 'elastic_container.yml'
  when: containerized_install
