######################################################
################# Setup Elasticsearch ################
######################################################
---

- name: "Create directories"
  file:
    group: "{{ es_group }}"
    mode: u+rw,g+rw
    owner: "{{ es_user }}"
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ es_config_dir }}"
    - "{{ es_config_dir }}/data"

- name: Install templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ es_config_dir }}/{{ item }}.yml"
    group: "root"
    owner: "root"
    mode: 0644
  with_items:
    - es-client
    - es-curator-config
    - es-curator_v1beta1
    - es-data-pdb
    - es-data
    - es-discovery-svc
    - es-master-pdb
    - es-master
    - es-svc

- name: Deploy
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ es_config_dir }}/{{ item }}.yml'
  with_items:
    - es-master
    - es-discovery-svc
    - es-svc
#    - es-client
#    - es-data

- name: Wait for deployment to finish
  command: 'kubectl --kubeconfig=/etc/kubernetes/admin.conf rollout status -f {{ es_config_dir }}/{{ item }}.yml'
  with_items:
    - es-master
#    - es-client
#    - es-data
