#######################################################
#################  Portainer Install ##################
#######################################################
---

- name: Download Portainer
  docker_image:
    name: 'portainer/portainer'

- name: 'Copy Portainer service file'
  template:
    src: 'portainer.service.j2'
    dest: '/etc/systemd/system/portainer.service'
    mode: 0644
    owner: '{{ rocknsm_user }}'
    group: '{{ rocknsm_user }}'

- name: 'Link Portainer service file'
  file:
    src: '/etc/systemd/system/portainer.service'
    dest: '/etc/systemd/system/rock.target.wants/portainer.service'
    owner: '{{ rocknsm_user }}'
    group: '{{ rocknsm_user }}'
    state: link
  notify: reload systemd

- name: 'Create new directories'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ rocknsm_dir }}/portainer/data"

- name: 'Create portainer log directory'
  file:
    path: '{{ portainer_log_dir }}'
    state: directory

- name: 'Copy Portainer compose file'
  template:
    src: 'portainer-compose.yml.j2'
    dest: "{{ rocknsm_dir }}/portainer/portainer-compose.yml"
    mode: 0644
    owner: '{{ rocknsm_user }}'
    group: '{{ rocknsm_user }}'

- name: 'Run portainer-compose.yml'
  docker_service:
    project_src: "{{ rocknsm_dir }}/portainer/"
    files: 'portainer-compose.yml'
    state: present

- name: 'Enable Portainer service'
  systemd:
    name: 'portainer'
    enabled: yes
    state: started
    daemon_reload: yes

...
