---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:
  children:
    master-servers:
      vars:
        home_net:
          - "192.168.0.0/16"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
        serivces_cidr: # Network Cidr for Metallb ie: "192.168.86.248/29"
        bpf_filter: "" # Only packets that match this filter will be processed by Moloch
        pcap_bpf_filter: "" # Packets that match this filter will NOT be saved to disk by Moloch
        es_mem: 2 # The amount of memory you want to assign to each elasticsearch instance
        es_masters: 3 # How many elasticsearch masters you would like to run
        es_datas: 0 # How many elasticsearch data nodes you would like to run
        elastic_pv_size: 6 # The amount of space allocated in GB to each persistent volume for Elasticsearch
        kafka_pv_size: 3 # The amount of space allocated in GB to each persistent volume for Kafka
        zookeeper_pv_size: 3 # The amount of space allocated in GB to each persistent volume for Zookeeper
        logstash_pv_size: 3 # The amount of space allocated in GB to each persistent volume for Logstash
        pcap_pv_size: 6 # The amount of space allocated in GB to each persistent volume for Moloch
        rockserver1.lan:
          ansible_user: root
          management_ipv4: # IP Address of node
          data_disk_devices:
          #- /dev/sdb <raw disk name>
    nodes:
      children:
        sensors:
          hosts:
            rocksensor1.lan:
              management_ipv4: # IP Address of node
              bro_workers: 2
              monitor_interfaces:
              #- eth0 <Interface Name>
              data_disk_devices:
              #- /dev/sdb <raw disk name>
          vars:
            # dns_ip: <192.168.1.50> The IP address of the sensor's DNS server
        servers:
          hosts:
            rockserver2.lan:
              ansible_user: root
              management_ipv4: # IP Address of node
              data_disk_devices:
              #- /dev/sdb <raw disk name>
          vars:
            # dns_ip: <192.168.1.50> The IP address of the sensor's DNS server
