#Configure Logstash
---

# copy pipeline configuration files
- name: "Install Bro-Kafka configuration for Logstash"
  copy:
    dest: "{{ logstash_pipeline_dir }}/kafka-bro.conf"
    group: "{{ logstash_group }}"
    mode: 416
    owner: "{{ logstash_user }}"
    src: logstash-kafka-bro.conf
  notify: "Restart Logstash"
  when: "with_bro and with_kafka"

- name: "Install Suricata-Kafka configuration for Logstash"
  copy:
    dest: ""{{ logstash_pipeline_dir }}/kafka-suricata.conf"
    group: "{{ logstash_group }}"
    mode: 416
    owner: "{{ logstash_user }}"
    src: 'logstash-kafka-suricata.conf'
  notify: "Restart Logstash"
  when: "with_suricata and with_kafka"

- name: "Install FSF-Kafka configuration for Logstash"
  copy:
    dest: "{{ logstash_pipeline_dir }}/kafka-fsf.conf"
    group: "{{ logstash_group }}"
    mode: 416
    owner: "{{ logstash_user }}"
    src: 'logstash-kafka-fsf.conf'
  notify: "Restart Logstash"
  when: "with_fsf and with_kafka"
