######################################################
################# Setup Logstash #####################
######################################################
---

- name: "Create Logstash config directory"
  file:
    path: "{{ item }}"
    mode: u+rw,g+rw
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    state: directory
  with_items:
    - "{{ logstash_dir }}"
    - "{{ logstash_dir }}/mnt"
    - "{{ logstash_pv_config_dir }}"
    - "{{ logstash_pv_data_dir }}"
    - "{{ logstash_pv_pipeline_dir }}"

- name: Install Logstash templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ logstash_dir }}/{{ item }}.yml"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  with_items:
    - logstash-deploy
    - pv-config
    - pv-data
    - pv-pipeline
    - pv-logs
    - pvc-config
    - pvc-data
    - pvc-pipeline
    - pvc-logs

- name: Copy Pipeline Files
  copy:
    src: "files/{{ item }}.conf"
    dest: "{{ logstash_pv_pipeline_dir }}/{{ item }}.conf"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  with_items:
    - kafka-bro
    - kafka-fsf
    - kafka-suricata

- name: Copy Config File
  template:
    src: "templates/logstash.yml.j2"
    dest: "{{ logstash_pv_config_dir }}/logstash.yml"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644

- name: Copy Pipeline File
  copy:
    src: "files/{{ item }}"
    dest: "{{ logstash_pv_config_dir }}/{{ item }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0644
  with_items:
    - pipelines.yml
    - log4j2.properties

- name: Deploy
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" create -f {{ logstash_dir }}/{{ item }}.yml'
  with_items:
    - pv-config
    - pv-data
    - pv-pipeline
    - pv-logs
    - pvc-config
    - pvc-data
    - pvc-pipeline
    - pvc-logs
    - logstash-deploy

- name: Wait for deployment to finish
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" rollout status -f {{ logstash_dir }}/logstash-deploy.yml'
