#Configure Logstash
---

# copy pipeline configuration files
- name: "Install Bro-Kafka configuration for Logstash"
  copy:
    dest: "{{ logstash_pipeline_dir }}/kafka-bro.conf"
    group: 1000
    mode: u+rw,g+rw,o+r
    owner: 1000
    src: 'logstash-kafka-bro.conf'
  notify: "Restart Logstash"
  when: "included_components.bro.enabled and included_components.kafka.enabled"

- name: "Install Suricata-Kafka configuration for Logstash"
  copy:
    dest: "{{ logstash_pipeline_dir }}/kafka-suricata.conf"
    group: 1000
    mode: u+rw,g+rw,o+r
    owner: 1000
    src: 'logstash-kafka-suricata.conf'
  notify: "Restart Logstash"
  when: "included_components.suricata.enabled and included_components.kafka.enabled"

- name: "Install FSF-Kafka configuration for Logstash"
  copy:
    dest: "{{ logstash_pipeline_dir }}/kafka-fsf.conf"
    group: 1000
    mode: u+rw,g+rw,o+r
    owner: 1000
    src: 'logstash-kafka-fsf.conf'
  notify: "Restart Logstash"
  when: "included_components.fsf.enabled and included_components.kafka.enabled"
