#Configure Logstash
---

# copy pipeline configuration files
- name: "Install Bro-Kafka configuration for Logstash"
  copy:
    dest: "{{ logstash_pipeline_dir }}/kafka-bro.conf"
    group: "{{ logstash_group }}"
    mode: u+rw,g+rw,o+r
    owner: "{{ logstash_user }}"
    src: 'kafka-bro.conf'

- name: "Install Suricata-Kafka configuration for Logstash"
  copy:
    dest: "{{ logstash_pipeline_dir }}/kafka-suricata.conf"
    group: "{{ logstash_group }}"
    mode: u+rw,g+rw,o+r
    owner: "{{ logstash_user }}"
    src: 'kafka-suricata.conf'

- name: "Install FSF-Kafka configuration for Logstash"
  copy:
    dest: "{{ logstash_pipeline_dir }}/kafka-fsf.conf"
    group: "{{ logstash_group }}"
    mode: u+rw,g+rw,o+r
    owner: "{{ logstash_user }}"
    src: 'kafka-fsf.conf'

- name: Restart Logstash
  systemd:
    name: logstash
    state: restarted
