---
- name: Kube | Init Kubernetes cluster
  shell: "kubeadm init --pod-network-cidr={{ kube_pod_cidr }} --kubernetes-version={{ kube_version }} | grep 'kubeadm join' | tee /etc/kubernetes/join-node.sh"
  register: init_kube_cluster_result
  failed_when: "'ERROR' in init_kube_cluster_result.stderr"

- name: Kube | Retrieve files
  fetch:
    src: "{{ item }}"
    dest: files/
    flat: yes
  with_items:
    - "{{ kubernetes_conf_file }}"
    - "/etc/kubernetes/join-node.sh"

- name: Retrieve generated credentials
  import_role:
    name: kubernetes/common
    tasks_from: creds

- name: 'Install pod network: kube-router'
  command: "kubectl apply -f {{ kube_dir }}/kube-flannel.yml"

- name: Kube | Wait for Master Node to be ready
  import_role:
    name: kubernetes/common
    tasks_from: kube_wait
  vars:
    type: "node"
    namespace: ""
    resource_name: "{{ ansible_fqdn }}"
    label: ""
