---
- name: Configure firewalld
  firewalld:
    port: "{{ item[1].port }}"
    source: "{{ item[0] }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_nested:
    - "{{ lighttpd_mgnt_nets }}"
    -
      - { port: "{{ lighttpd_firewall_port }}/tcp" }
...
