---

#######################################
# Perform layer 3 functionality test  #
# and IP address verify               #
#######################################
#The below code verifies that the management IPV4 addresses are valid IPs
#Meaning that they have 4 octets and only contain numbers in those octets
- name: Verify IP scheme (111.111.111.111)
  fail:
    msg: "{{ item }} is not a valid IP"
  when: (item | regex_search('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b')) != item
  with_items: "{{ management_ipv4 }}"
  changed_when: False

#The below code verifies that the management IPV4 addresses are valid IP ranges
#This means that each octet ranges 0-255 nothing more, nothing less
- name: Verify valid IP range (0-255)
  fail:
    msg: "{{ item }} is not a valid IP range"
  when: item.split('.')[0] | int > 255 or item.split('.')[1] | int > 255 or item.split('.')[2] | int > 255 or item.split('.')[3] | int > 255
  with_items: "{{ management_ipv4 }}"
  changed_when: false

- name: ping all ips in inventory
  shell: "ping -c 1 {{ item }}"
  with_items: "{{ groups['nodes'] }}"
  changed_when: False

- name: ping google DNS by IP
  shell: "ping -c 1 8.8.8.8"
  changed_when: False

- name: ping www.Google.com
  shell: "ping -c 1 www.google.com"
  changed_when: False

...
