---

######################################################
# Perform Elasticsearch resource requirements checks #
######################################################

- name: Verify Elasticsearch heap memory is less than half of physical RAM
  fail:
    msg: 'Ensure your elasticsearch memory is half your physical RAM or less. See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html'
  when: inventory_hostname in groups['elasticsearch'] and (ansible_memory_mb.real.total / 2) < elastic_mem * 1024

- name: Verify Elasticsearch memory does not exceed 26GB
  fail:
    msg: 'For optimization, Elasticsearch memory should not exceed 26GB. See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html'
  when: inventory_hostname in groups['elasticsearch'] and elastic_mem > 26

- name: Verify double elastic_mem is available on the machine
  fail:
    msg: "elastic_mem (elasticsearch memory) consumes elastic_mem*2 for performance reasons. Your host has {{ ansible_memory_mb.real.total * 1024 }} and you have requested {{ elastic_mem * 2 * 1024 }}MB for Elasticsearch."
  when: inventory_hostname in groups['elasticsearch'] and (elastic_mem * 2 * 1024) > ansible_memory_mb.real.total

- name: Verify Elasticsearch Maximum Cores does not exceed total cores available.
  fail:
    msg: "You have specified a maximum number of cores for ElasticSearch that exceeds total cores available."
  when: inventory_hostname in groups['elasticsearch'] and ( ansible_processor_cores * ansible_processor_count ) > elastic_cpu_maximum  
...
