######################################################
################# Setup Kibana #######################
######################################################
---

- name: "Create config directory"
  file:
    path: "{{ kibana_dir }}"
    state: directory
    owner: root
    group: root
    mode: u+rw,g+rw

- name: Install templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ kibana_dir }}/{{ item }}.yml"
    group: root
    owner: root
    mode: 0644
  with_items:
    - kibana-deploy
    - kibana-svc

- name: Deploy
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ kibana_dir }}/{{ item }}.yml'
  with_items:
    - kibana-deploy
    - kibana-svc

- name: Wait for deployment to finish
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" rollout status -f {{ kibana_dir }}/kibana-deploy.yml'
