---
######################################################
############### Setup Dnsmasq container ###############
######################################################

- name: Install Dnsmasq
  yum:
    name: dnsmasq
    state: installed

- name: Install BIND-Utils
  yum:
    name: bind-utils
    state: installed

- name: 'Create new directories'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ rocknsm_dir }}/dnsmasq/data"

- name: Start dnsmasq and enable it
  service:
    name: dnsmasq
    state: started
    enabled: true
