######################################################
################# Setup Kafka ########################
######################################################
---

- name: "Create Directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u+rw,g+rw
  with_items:
    - "{{ kafka_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ kafka_config_dir}}"

- name: Install Templates
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "{{ kafka_dir }}/{{ item }}.yml"
    group: root
    owner: root
    mode: 0644
  with_items:
    - kafka-deploy
    - kafka-svc
    - kafka-dockerfile

- name: Install Properties File
  template:
    src: "templates/server.properties.j2"
    dest: "{{ kafka_config_dir }}/server.properties"
    group: root
    owner: root
    mode: 0644

- name: Copy Files
  copy:
    src: "files/start-kafka.sh"
    dest: "{{ kafka_dir }}/start-kafka.sh"
    group: root
    owner: root
    mode: 0644

- name: Build Container
  docker_image:
    name: "{{ kafka_container_name }}"
    pull: yes
    state: present
    path: "{{ kafka_dir }}"
    dockerfile: kafka-dockerfile.yml

- name: Deploy
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" create -f {{ kafka_dir }}/{{ item }}.yml'
  with_items:
    - kafka-deploy
    - kafka-svc

- name: Wait for deployment to finish
  command: 'kubectl --kubeconfig="/etc/kubernetes/admin.conf" rollout status -f {{ kafka_dir }}/{{ item }}.yml'

- name: Create Topics
  command: >
    docker exec {{ kafka_container_name }} {{ kafka_install_dir }}/bin/kafka-topics.sh
      --zookeeper zookeeper:{{ zookeeper_port }}
      --create
      --replication-factor 1
      --topic {{ item }}-raw
      --partisions 1
  with_items:
    - bro
    - suricata
    - fsf
