######################################################
################# Setup Kafka ########################
######################################################
---

- name: "Create Directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u+rw,g+rw
  with_items:
    - "{{ zookeeper_dir }}"
    - "{{ kafka_dir }}"

- name: Install Kafka Templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ kafka_dir }}/{{ item }}"
    group: root
    owner: root
    mode: 0644
  with_items:
    - deploy.yml
    - kafka-service.yml
    - kafka-pvc-data.yml
    - server.properties
    - zookeeper-pvc-data.yml
    - zookeeper_config_map

- name: Install Zookeeper Templates
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ zookeeper_dir }}/{{ item }}"
    group: root
    owner: root
    mode: 0644
  with_items:
    - zookeeper-pvc-data.yml
    - zookeeper_config_map

- name: Flush Config Maps
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" delete configmap {{ item }}'
  ignore_errors: yes
  with_items:
    - kafka-config-map
    - zookeeper-config-map

# This task uses kafka_config_map and feeds it into Kubernetes as a configuration map which it then uses
# to build the container
- name: Create Kafka Config
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" create configmap kafka-config-map --from-file {{ kafka_dir }}/server.properties'

# This does the same, but with Zookeeper
- name: Create Zookeeper Config
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" create configmap zookeeper-config-map --from-file {{ zookeeper_dir }}/zookeeper_config_map'

- name: Wait for PVCs to Bind
  shell: |
    kubectl --kubeconfig="{{ kubernetes_conf_file }}" apply -f {{ item.dir }}/{{ item.file }}.yml
    while [ $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get -f {{ item.dir }}/{{ item.file }}.yml | tail -n +2 | awk '{ print $2 }') != 'Bound' ]; do
      echo -n .;
      sleep 1;
    done;
    while [ $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get ep | grep $(kubectl --kubeconfig="{{ kubernetes_conf_file }}" get -f {{ item.dir }}/{{ item.file }}.yml | tail -n +2 | awk '{ print $1 }') | wc -l) == '0' ]; do
      echo -n .;
      sleep 1;
    done;
  with_items:
    - { dir: "{{ kafka_dir }}", file: 'kafka-pvc-data' }
    - { dir: "{{ zookeeper_dir }}", file: 'zookeeper-pvc-data' }

- name: Run the kafka/zookeeper deploy file
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" apply -f {{ kafka_dir }}/deploy.yml'

- name: Wait for deployment to finish
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" rollout status -f {{ kafka_dir }}/deploy.yml'

- name: Deploy Kafka Service
  command: 'kubectl --kubeconfig="{{ kubernetes_conf_file }}" apply -f {{ kafka_dir}}/kafka-service.yml'

#- name: Create Topics
#  command: >
#    docker exec {{ kafka_container_name }} {{ kafka_install_dir }}/bin/kafka-topics.sh
#      --zookeeper zookeeper:{{ zookeeper_port }}
#      --create
#      --replication-factor 1
#      --topic {{ item }}-raw
#      --partisions 1
#  with_items:
#    - bro
#    - suricata
#    - fsf
