######################################################
##################### Setup Kafka ####################
######################################################
---

#- include_tasks: 'kafka_bare-metal.yml'
#  when: not containerized_install

- include_tasks: 'kafka_container.yml'
  when: containerized_install
