%YAML 1.1
---
haproxy_container_name: 'rock-haproxy'
haproxy_log_dir: '/var/log/haproxy'
#### HAProxy configuration variables ####
haproxy_stats_port: '8080'
elastic_lb_port: '9200'
haproxy_mgnt_nets: "{{ rock_mgmt_nets }}"
...
