# Please note that I have included the "disable_action" key for testing purposes.
# Setting this key to "true" will prevent that action from running.
actions:
  1:
    action: delete_indices
    description: >-
      Delete all marvel indices older than one day.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: .marvel-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
  2:
    action: delete_indices
    description: >-
      Delete indices older than 60 days (based on index name), for logstash-prefixed
      indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 60
  3:
    action: close
    description: >-
      Close indices older than 15 days (based on index name), for logstash- prefixed indices.
    options:
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 15
  4:
    action: replicas
    description: >-
      Reduce the replica count per-shard to 0 for all indices.
    options:
      count: 0
      wait_for_completion: True
      disable_action: False
