---

- name: Enable modules
  modprobe:
    name: "br_netfilter"
    state: present

- file:
    path: /etc/modules-load.d/99-k8.conf
    state: touch
    owner: root
    group: root
    mode: 0644

- lineinfile:
    path: /etc/modules-load.d/99-k8.conf
    line: 'br_netfilter'

...
