---

# GONODE is a go template which extracts the Ready and Status fields from the api in json format.
# Node Array -> Status -> Condition Array -> Type field (Ready) and Status Field
# "kubectl get nodes -o json" will return the full json structure

- name: Kube | Wait for Node
  shell: |
    {% raw %}
    GONODE='{{range .items}}{{range .status.conditions}}{{if and (eq (.type) ("Ready")) (eq (.status) ("False"))}}{{.type}}{{end}}{{end}}{{end}}'
    kubectl get no --all-namespaces -o go-template="$GONODE"
    {% endraw %}
  register: output
  until: output.stdout == ""
  retries: 30
  delay: 15
  #ignore_errors: no