---
- name: Create Gluster Directory
  file:
    path: "{{ gluster_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Install Templates
  template:
    src: templates/{{ item }}.j2
    dest: "{{ gluster_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - topology.json
    - storage-class.yml
    - heketi.json.template

- name: Copy Files
  copy:
    src: "{{ item }}"
    dest: "{{ gluster_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:    
    - gk-deploy
    - deploy-heketi-deployment.yaml
    - glusterfs-daemonset.yaml
    - heketi-deployment.yaml
    - heketi-service-account.yaml
    - test-storage.yml

- name: Change gk deploy perms
  file:
    path: "{{ gluster_dir }}/gk-deploy"
    mode: 0755
    owner: root
    group: root