---
- name: Deploy Heketi
  command: 'kubectl create -f {{ gluster_dir }}/heketi-deployment.json'
  when: cleanup_bootstrap_result.rc == 0

- name: Gluster | Wait for Heketi Deployment
  shell: |
    {% raw %}
    GO='{{.metadata.name}}'
    kubectl get  deployment heketi -o go-template="$GO"
    {% endraw %}
  register: output
  until: output.stdout == 'heketi'
  retries: 30
  delay: 15
  when: "(deploy_bootstrap_result.changed) and (deploy_bootstrap_result.rc == 0)"

- name: Gluster | Wait for Pod
  include_role:
    name: kubernetes/common
    tasks_from: pod_wait

- name: Get Cluster IP
  include_tasks: cluster_info.yml

- name: Set Cluster IP in Storage Class
  replace:
    path: '{{ gluster_dir }}/storage-class.yml'
    regexp: 'heketi_cluster_ip'
    replace: '{{ heketi_ip.stdout }}'

- name: Deploy Storage Class
  command: "kubectl create -f {{ gluster_dir }}/storage-class.yml"