#######################################################
###################  Gluster Install ##################
#######################################################
---

# Uninstall GlusterFS
- include_tasks: remove.yml
  when: remove
# Install GlusterFS, this will fail spectacularly if this is not a fresh install,
# or remove is not run first

- include_tasks: repo.yml
- include_tasks: packages.yml
- include_tasks: kernel_mods.yml
- include_tasks: sysctl.yml

- include_tasks: files.yml
  when: inventory_hostname in groups['master-server'] 

- name: Label Nodes
  command: "kubectl label node {{ item }} storagenode=glusterfs --overwrite=true"
  with_items:
    - "{{ groups['master-server'] }}"
    - "{{ groups['nodes'] }}"

- name: Deploy GlusterFS Daemonset
  include_tasks: daemonset.yml
  when: inventory_hostname in groups['master-server']

- name: Deploy Heketi Service Account
  include_tasks: heketi_account.yml
  when: inventory_hostname in groups['master-server'] 

- name: Bootstrap Heketi
  include_tasks: heketi_bootstrap.yml
  when: inventory_hostname in groups['master-server']

- name: Set Heketi Cli Environment Variable
  include_tasks: heketi_cli_env.yml

- name: Wipe Raw Disks
  include_tasks: wipe.yml
  when: "(gluster_created_daemonset_result.changed) and (gluster_created_daemonset_result.rc == 0)"

- name: Setup Heketi Storage
  include_tasks: heketi_storage_setup.yml
  when: inventory_hostname in groups['master-server']

- name: Setup Heketi Deployment
  include_tasks: heketi_deploy.yml
  when: inventory_hostname in groups['master-server'] 

...
