# Uninstall GlusterFS

- name: Flush GlusterFS
  shell: "kubectl delete all,service,jobs,deployment,secret --selector glusterfs"
  when: inventory_hostname in groups['master-server']

- name: Flush Heketi Bootstrap
  shell: "kubectl delete all,service,jobs,deployment,secret --selector deploy-heketi"
  when: inventory_hostname in groups['master-server']

- name: Uninstall GlusterFS client
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - glusterfs-client
    - heketi-client

- name: Remove Centos repo
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "centos-release-gluster{{ centos_gluster_ver }}"
  #when: ansible_distribution == 'CentOS'

- name: "Remove RedHat repo"
  yum_repository:
    baseurl: "http://mirror.centos.org/centos/7/storage/x86_64/gluster-{{ gluster_ver }}/"
    description: "Gluster repository"
    gpgcheck: no
    name: CentOS-Gluster-3.10
    state: absent
  when: ansible_distribution == 'RedHat'

- name: Remove possible artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/heketi
    - /var/lib/glusterfs
    - /var/lib/glusterd
    - /etc/glusterfs

- name: Remove Gluster Directory
  file:
    path: "{{ gluster_dir }}"
    state: absent
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups['master-server']
