apiVersion: v1
kind: Service
metadata:
  labels:
    component: moloch
  name: moloch
spec:
  ports:
  - name: "webgui"
    port: 80
    targetPort: "webgui"
  selector:
    component: moloch
  type: LoadBalancer
