---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:

  children:

    # Role specific breakout

    kubernetes:
      children:
        master-servers:
        nodes:

    ceph:
      children:
        master-servers:

    kibana:
      children:
        master-servers:

    elasticsearch:
      children:
        master-servers:

    logstash:
      children:
        master-servers:

    suricata:
      children:
        master-servers:

    kafka:
      children:
        master-servers:

    bro:
      children:
        master-servers:

    moloch:
      children:
        master-servers:

    master-servers:

      vars:
        home_net:
          - "192.168.0.0/16"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
        services_cidr: "10.11.4.240/29"
        bpf_filter: ""
        es_mem: 2
        es_masters: 3
        es_datas: 0
        elastic_pv_size: 1000
        kafka_pv_size: 10
        zookeeper_pv_size: 10
        logstash_pv_size: 10
        pcap_pv_size: 100000

      hosts:
        hwserver1.lan:
          ansible_hostname: hwserver1.lan
          ansible_user: root
          ansible_connection: ssh
          management_ipv4: 10.11.4.164
          data_disk_devices:
          - /dev/sdb
          - /dev/sda

    nodes:

      children:

        sensors:

          hosts:
            hwsensor1.lan:
              ansible_hostname: hwsensor1.lan
              ansible_connection: ssh
              management_ipv4: 10.11.4.141
              bro_workers: 24
              monitor_interfaces:
              - lo
              data_disk_devices:
              - /dev/sdb

        servers:

          hosts:
            hwsensor2.lan:
              ansible_hostname: hwsensor2.lan
              ansible_user: root
              ansible_connection: ssh
              management_ipv4: 10.11.4.140
              monitor_interfaces:
                - lo
              data_disk_devices:
              - /dev/sdb
              - /dev/sdc
              - /dev/sdd

            hwserver2.lan:
              ansible_hostname: hwserver2.lan
              ansible_user: root
              ansible_connection: ssh
              management_ipv4: 10.11.4.143
              data_disk_devices:
              - /dev/sdb
