# The main difference between primary and secondary servers is that the primary
# server will run things like portainer and harbor. The secondary servers are
# only there to provide extra elasticsearch computing power.

---

- hosts: primary-servers
  roles:
    - common
    - docker
# kibana and portainer must come before haproxy as haproxy cannot run without
# being able to contact at least one of each backend servers (1 kibana, 1 portainer,
# 1 elasticsearch)
    - kibana
    - portainer
# haproxy must come before elasticsearch. The host running ansible will not
# beable to contact elasticsearch without haproxy running, this is required
# for elasticsearch's main tasks to complete. Adding haproxy to elasticsearch's
# dependencies is not an option due to ansible installing haproxy on every host
# that elasticsearch is assigned to.
    - haproxy
    - elasticsearch
    - logstash

    # Harbor must run last so that it uploads all containers installed on the machine.
    # Harbor has compose file issue, disabling for now
    #- harbor
