---

- hosts: sensors

  roles:
    - common
    - sensor-common

    # Containerized_install: if true, all services are docker containers. Otherwise, services installed bare metal
    - { role: docker, when: containerized_install }
    - { role: suricata, when: with_suricata }
    - { role: kafka, when: with_kafka }
    - { role: zookeeper, when: with_zookeeper }
    - { role: filebeats, when: with_filebeats }
    # TODO: Bro was seriously pissing me off. Just errors upon errors upon errors... upon errors so I disabled it
    # so I could commit this nonsense. I'll deal with it later.
    #- { role: bro, when: with_bro }

