# site.yml is the overall playbook, but all it does is include the other playbooks that are part of the site. For more
# information about the structure see:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
# http://docs.ansible.com/ansible/latest/intro_inventory.html
# We follow the guidance to include naming conventions there.

---

- name: Install Controller Dependancies
  hosts: localhost
  tasks:
  - name: Install python-netaddr package
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - sshpass
      - python-netaddr
      - bind-utils

- name: Perform preflight checks
  hosts: all
  roles:
    - preflight_checks
  tags: preflight

- name: Common Setup
  hosts:
    - master-server
    - nodes
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - common
    - chrony
  tags:
    - common

- name: Generate SSH keys
  hosts:
    - localhost
    - all
  connection: ssh
  any_errors_fatal: true
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['all'] }}"
    # See https://www.linkedin.com/pulse/winning-ansible-how-manipulate-items-list-carlos-nunez/
    # for explanation
    ssh_short_known_hosts: "{{ groups['all'] | map('regex_replace','(.lan)','' ) | list }}"
  tasks:
    - import_tasks: generate_ssh_keys.yml
  tags:
    - genkeys

- name: Configure kube master
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - kubernetes/common
    - kubernetes/master
  tags:
    - kube-master

- name: Configure kube nodes
  hosts:
    - remote-sensors
    - sensors
    - servers
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - kubernetes/common
    - kubernetes/node
  tags:
    - add-node
    - kube-node

- name: Setup Ceph
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - ceph
  tags:
    - ceph

- name: Deploy Elasticsearch
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- name: Deploy Logstash
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - logstash
  tags:
    - logstash

- name: Deploy Kibana
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - kibana
  tags:
    - kibana

- name: Deploy metricbeats
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - metricbeat
  tags:
    - metricbeat

- name: Deploy Kafka
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - { role: kafka, remote: true }
    - { role: kafka, remote: false }
  tags:
    - kafka

- name: Deploy Bro
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - bro
  tags:
  - bro

- name: Deploy Moloch
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - moloch
  tags:
    - moloch

- name: Deploy Suricata
  hosts: master-server
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - suricata
  tags:
    - suricata

- name: Deploy Stenographer
  hosts:
    - sensors
    - remote-sensors
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - stenographer
  tags:
    - stenographer

- name: Deploy Docket
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - setup:
  roles:
    - docket
  tags:
    - docket

...
