# site.yml is the overall playbook, but all it does is include the other playbooks that are part of the site. For more
# information about the structure see:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
# http://docs.ansible.com/ansible/latest/intro_inventory.html
# We follow the guidance to include naming conventions there.

---

- name: Generate SSH keys
  hosts:
    - localhost
    - all
  connection: ssh
  vars:
    ssh_known_hosts_command: "ssh-keyscan -T 10"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    ssh_known_hosts: "{{ groups['all'] }}"

    # See https://www.linkedin.com/pulse/winning-ansible-how-manipulate-items-list-carlos-nunez/
    # for explanation
    ssh_short_known_hosts: "{{ groups['all'] | map('regex_replace','(.lan)','' ) | list }}"
  tasks:
    - import_tasks: generate_ssh_keys.yml
      when: genkeys is defined and genkeys

- name: Common Setup
  hosts: all
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - common
    - chrony
  tags:
    - common

- name: Configure kube master
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - kubernetes/common
    - kubernetes/master
  tags:
    - kube-master

- name: Configure kube nodes
  hosts: nodes
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - kubernetes/common
    - kubernetes/node
  tags:
    - add-node
    - kube-node

- name: Setup Ceph
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - ceph
  tags:
    - ceph

- name: Deploy Elasticsearch
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - elasticsearch
  tags:
    - elasticsearch

- name: Deploy Logstash
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - logstash
  tags:
    - logstash

- name: Deploy Kibana
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - kibana
  tags:
    - kibana

- name: Deploy metricbeats
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - metricbeat
  tags:
    - metricbeat

- name: Deploy Kafka
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - kafka
  tags:
    - kafka

- name: Deploy Bro
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - bro
  tags:
  - bro

- name: Deploy Moloch
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - moloch
  tags:
    - moloch

- name: Deploy Suricata
  hosts: master-servers
  gather_facts: no
  pre_tasks:
    - setup:
  roles:
    - suricata
  tags:
    - suricata

...
