# site.yml is the overall playbook, but all it does is include the other playbooks that are part of the site. For more
# information about the structure see:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
# http://docs.ansible.com/ansible/latest/intro_inventory.html
# We follow the guidance to include naming conventions there.

---

- hosts: all

  tasks:

  # Useful for debugging, uncomment if you don't need it. This will post all
  # ansible related variables to the file /tmp/ansible.all
  #- name: Dump all vars
  #  action: template src=templates/dumpall.j2 dest=/tmp/ansible-site.all

- import_playbook: primary-servers.yml
- import_playbook: sensors.yml
- import_playbook: configure_services.yml
