# site.yml is the overall playbook, but all it does is include the other playbooks that are part of the site. For more
# information about the structure see:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
# http://docs.ansible.com/ansible/latest/intro_inventory.html
# We follow the guidance to include naming conventions there.

---
- hosts: all
  tasks:
  roles:
    - common
    - chrony

#- name: Reset Kube
#  hosts: 
#    - master-server
#    - nodes
#  roles:
#    - kubernetes/reset
#  vars:
#    kubeadm_reset: true
#  tags:
#  - kube-reset

- name: Configure kube master
  hosts: master-server
  roles:
    - kubernetes/common
    - kubernetes/master
  tags:
  - kube-master

- name: Configure kube nodes
  hosts: nodes
  roles:
    - kubernetes/common
    - kubernetes/node
  tags:
  - add-node

#- name: Setup Ceph
#  hosts:
#  - master-server
#  - nodes
#  roles:
#    - ceph

- name: Setup GlusterFS
  hosts:
  - master-server
  - nodes
  roles:
    - gluster
  tags:
    - gluster

- name: Deploy Elasticsearch
  hosts: master-server
  roles:
    - elasticsearch
  tags:
    - elasticsearch

...
