######################################################
################# Setup Zookeeper ################
######################################################
---

#- include_tasks: 'zookeeper_bare-metal.yml'
#  when: not containerized_install

- include_tasks: 'zookeeper_container.yml'
  when: containerized_install
