---
######################################################
############### Setup Zookeeper container ###############
######################################################

- name: 'Install Zookeeper service file'
  template:
    src: 'zookeeper.service.j2'
    dest: '/etc/systemd/system/zookeeper.service'
    mode: 0644
    owner: root
    group: root
  notify: reload systemd

- name: 'Create new directories'
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ rocknsm_dir }}/zookeeper/data"

- name: 'Copy Zookeeper dockerfile'
  template:
    src: 'zookeeper-dockerfile.j2'
    dest: "{{ rocknsm_dir }}/zookeeper/zookeeper-dockerfile.j2"
    mode: 0644
    owner: root
    group: root

- name: 'Build Zookeeper container'
  docker_image:
    name: 'rocknsm/zookeeper'
    pull: yes
    state: present
    path: "{{ rocknsm_dir }}/zookeeper/"
    dockerfile: 'zookeeper-dockerfile.j2'
  when: rock_online_install

- name: 'Copy Zookeeper docker compose file'
  template:
    src: 'zookeeper-compose.yml.j2'
    dest: "{{ rocknsm_dir }}/zookeeper/zookeeper-compose.yml.j2"
    mode: 0644
    owner: root
    group: root

- name: 'Run Zookeeper docker compose file'
  docker_service:
    project_src: "{{ rocknsm_dir }}/zookeeper/"
    files: 'zookeeper-compose.yml.j2'
    state: present

- name: 'Enable Zookeeper service'
  service:
    name: 'zookeeper'
    enabled: yes
...
