---
# TODO: Move this to `/etc/docket` by default
- name: docket | set production docket config
  template:
    src:  docket_prod.yaml.j2
    dest: /etc/docket/prod.yaml
  notify:

- name: docket | enable redis
  service:
    name: redis
    enabled: yes
  notify: docket | restart redis

- name: docket | enable docket celery service
  service:
    name: docket-celery
    enabled: yes
  notify: docket | restart docket celery

- name: docket | enable docket uwsgi service
  service:
    name: docket
    enabled: yes
  notify: docket | restart docket uwsgi
